import './js/fetchAPI';
import './js/refs';
import './js/modalMovie';
import './js/modalStudents';
import './js/pagination';
import './js/filmSearch';
import './js/filmCard';
import './js/api-vars';
import './js/fetchGenres';
import './js/localStorage';
import './js/backToTopBtn';
import './js/switchDayNight';
import './js/scrollToTop';
import './js/trailer';
// import './js/watched';
// import './js/library';
import './js/loader';
